### ISSUE TITLE
Rendered stream is fuzzy

### ISSUE THREAD

**Issue by FashionChain0622** [adamrehn/ue4-example-dockerfiles#1]
I build all docker images successfully, but when I open the pixel stream in a browser, the video is corrupted like below.
![image](https://user-images.githubusercontent.com/9649526/119638755-89e04b00-be49-11eb-91d1-af4096e7b44f.png)
How can I fix this problem?
My GPU is NVIDIA Tesla T4

**Comment by adamrehn** [comment]
I'm not sure what might be causing that corruption. I'd recommend upgrading to Unreal Engine 4.27 to see if that resolves the issue, since the Pixel Streaming system underwent significant improvements for 4.27.0 and a lot of long-standing bugs were fixed. In any case, this issue is unrelated to the Dockerfiles in this repository and is best addressed elsewhere.
